/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'reecr' at '2/6/16 8:32 PM' with Gradle 2.6
 *
 * @author reecr, @date 2/6/16 8:32 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return false;
    }
}
