import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'reecr' at '2/6/16 8:32 PM' with Gradle 2.6
 *
 * @author reecr, @date 2/6/16 8:32 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertFalse("someLibraryMethod should return 'false'", classUnderTest.someLibraryMethod());
    }
}
